CHANGELOG.md
ddl/check.lua
test/check_schema_test.lua
test/set_schema_test.lua

Tarantool allows space format to have custom fields. And users say it
may be valuable. This patch allows to add custom `space.format` fields,
for example
```lua
spaces = {
test = {
format = {{
name = 'size',
type = 'number',
scale = 'bananas',
}},
}
}
```
The only restriction is that a custom field must be a string.
Close #36

Allow custom fields in space format

---

.github/workflows/publish.yaml
.github/workflows/test.yml
CHANGELOG.md
ddl.lua
test/set_schema_test.lua

- Forbid redundant keys in schema top-level
- Make `spaces` table mandatory
So the only valid schema format is `{spaces = {...}}`.
Related to https://github.com/tarantool/cartridge/issues/1117

Make schema top-level keys validation stricter

---

.github/workflows/test.yml

This patch bumps Tarantool versions to be tested in CI.

update tarantool versions in CI targets

---

CHANGELOG.md
ddl.lua
ddl/db.lua
test/check_schema_test.lua
test/db.lua
test/set_schema_test.lua

Physical creation of schema for test is the most painful part of
ddl module. DDL is replicated and it's quite awful when another
instances could see test schema modification.
This patch enables using of signle-yield transacational DDL
statements that allows to create empty spaces and indexes
transactionally. But since this schema modifications is needed
only for tests we rollback them at the end. So, another instances
don't see any test changes after this patch. For details see [1].
[1] tarantool/tarantool#4083
Closes #46

Use transactional ddl when applying schema

---

.github/workflows/test.yml
.gitignore
CHANGELOG.md
CMakeLists.txt
README.md
cartridge/roles/ddl-manager.lua
test/db.lua
test/entrypoint/srv_basic.lua
test/helper.lua
test/role_test.lua

This is an extended version of #51.
* The role is renamed back to `ddl-manager`.
* Implement `stop()` callback for the sake of reloadability.
* Remove from CI the other `ddl` version installed by cartridge.
* Add the role to the cmake installer (it was missing in the original patch).
* Provide the API to be used in cartridge and test it a lot:
```lua
get_clusterwide_schema_yaml() -- return "spaces: {}"
get_clusterwide_schema_lua() -- return {spaces = {}}
set_clusterwide_schema_yaml("spaces: {}") -- return true
set_clusterwide_schema_lua({spaces = {}}) -- return true
check_schema_yaml("spaces: {}") -- return true
check_schema_lua({spaces = {}}) -- return true
```
Close #50

Add the ddl-manager from cartridge as a new role

---

CHANGELOG.md
cartridge/roles/ddl-manager.lua
test/db.lua
test/role_test.lua
test/set_schema_test.lua

If one applies an empty schema using the 'ddl-manager' role API, put in the clusterwide configuration an example instead.
I didn't forget about
Part of https://github.com/tarantool/cartridge/issues/1085
See also https://github.com/tarantool/cartridge/pull/1194

Store schema example in the clusterwide config

---

CMakeLists.txt
ddl/get.lua
ddl/set.lua

In commit "Top-level architecture refactoring"
(9171f72eba03c0478f1108bd280fac19311a4c84)
some functions were left commented out.
This commit cleanup dead code.
Closes #63

Remove dead code

---

CHANGELOG.md
README.md
test/set_sharding_key_test.lua

This commit exposes space name `_ddl_sharding_key` and it's format as a
part of public API. Everyone allowed to get and set sharding keys there
using DDL module or it's own code. Rigth now space `_ddl_sharding_key`
is used in `migrations` module to register sharding key [1].
1. https://github.com/tarantool/migrations/blob/master/migrator/utils.lua#L20-L39

Make a space with sharding keys as a part of API

---

README.md

Space `_ddl_sharding_key` and it's format are a part of DDL API.
Users may use DDL spaces even no sharding keys or sharding spaces
are defined in DDL schema, so we need always create `_ddl_sharding_key`.
This behavior tested in `set_sharding_key.test_no_sharding_spaces`.

Update info in README about _ddl_sharding_key space creation

---

.github/workflows/test.yml

It is better to stick to a latest tagged version, that considered as
stable, than to a current development version.

Switch to tagged version of GH action for source code checkout

---

test/bucket_id_test.lua
test/check_schema_test.lua
test/check_sharding_metadata_test.lua
test/helper.lua
test/set_schema_test.lua
test/set_sharding_metadata_test.lua

Now every test file defines it's own test space format. However all
these formats are similar and we can define once in helpers to avoid
code duplication.

test: define test space format once

---

.github/workflows/test.yml
README.md
ddl/cache.lua
ddl/get.lua
ddl/utils.lua
test/bench_cache.lua
test/cache_test.lua

The ddl.bucket_id() function needs to know a sharding function.
It is costly to obtain the function declaration /
definition stored in the _ddl_sharding_func space.
Cache contains:
raw_tuple - raw sharding metadata, used for get_schema()
parsed_func_name - parsed dot notation (like {'foo', 'bar'})
callable - function ready to call, this offloads using of loadstring()
error - string with an error: not nil only if setting callable fails
Cache will be rebuilded if:
* _ddl_sharding_func space changed: cache sets _ddl_sharding_func:on_replace
trigger
* schema changed: cache checks box.internal.schema_version changes
This patch does not serve hot reload techniques.
This entails an on_replace trigger duplication if hot reload occurs.
Hot reload support will be done in separate task: …

Add caching of sharding function

---

CHANGELOG.md
ddl/check.lua
test/check_sharding_metadata_test.lua
test/helper.lua
test/set_sharding_metadata_test.lua

`ddl.set_schema(schema)` fails with schema containing `vshard` sharding func.
It doesn't matter if vshard module was required on ddl storage.
The problem is that checking sharding function in dot notation
is performed by checking each item separated by dot in sharding
function name, item should be contained in global environment `_G`.
But in vshard sharding function case item `routers` (field in `vshard` table)
is an empty table because we store schema info on storage.
So field `bucket_id_strcrc32` is nil in 'vshard.router.bucket_id_strcrc32'.
Solution is to treat vshard sharding functions as separate cases.
Closes #91

fix: check for vshard sharding func

---

.github/workflows/reusable_test.yml
CMakeLists.txt

The idea of this workflow is to be a part of the 'integration.yml'
workflow from the tarantool repo to verify the integration of the
ddl module with an arbitrary tarantool version.
Tested [here](https://github.com/tarantool/tarantool/actions/runs/3752256684)
Tested negatively [here](https://github.com/tarantool/tarantool/actions/runs/3752394234)
Part of tarantool/tarantool#6619

ci: add reusable testing workflow for ddl module

---

.github/workflows/publish.yaml
CHANGELOG.md
ddl.lua
ddl/version.lua

Add versioning support, now the module api has `_VERSION` hardcoded variable. Is part of the task [1].
1. https://github.com/tarantool/roadmap-internal/issues/204

api: add hardcoded versioning support

---

.github/workflows/test.yml

There is known unsolved problem with Ubuntu Jammy [1].  Because of this, `tarantool 2.6` is installed in all cases. During tests it turns out that `builtin#95 table.clear` is [nil](https://github.com/tarantool/ddl/actions/runs/4518349665/jobs/7958166174#step:15:3) on the installed tarantool 2.6, which causes problems in ci job `test`.
Also the expected tarantool version was not installed in job `benchmark` before this patch.
1. tarantool/setup-tarantool/issues/36

ci: workaround setup-tarantool problem with Jammy

---

CHANGELOG.md
ddl.lua
ddl/check.lua
ddl/version.lua
test/check_schema_test.lua
test/get_schema_test.lua
test/set_schema_test.lua

It is the compatibility layer for Tarantool spaces created not through ddl: users are not encouraged to create fieldno path indexes in ddl schema explicitly, since we do not support them as sharding keys.
Closes #108

Basic fieldno path support for indexes

---

CHANGELOG.md
ddl/check.lua
ddl/db.lua
ddl/set.lua
test/check_schema_test.lua
test/set_schema_test.lua

Add exclude_null support for indexes. The option was introduced in Tarantool 2.8.1 [1] for nullable TREE indexes.
Since ddl approach is "require explicit fields rather than fill with sane defaults" (for example, one must explicitly set is_nullable for each field), we do not add "if exclude_null=true and is_nullable is not provided, set is_nullable=true" rule from the core Tarantool [1]: we require to explicitly specify both fields, if one wants to use exclude_null features.
1. https://github.com/tarantool/tarantool/commit/17c9c034933d726925910ce5bf8b20e8e388f6e3
Closes #110

ddl: add exclude_null support for indexes

---

deps.sh

"Test" workflow installs latest luatest, yet "Reusable test" installs luatest 0.5.7. Latest e2cdb560 commit had introduced tests which use some luatest master utils. These tests fails on "Reusable test", see [1].
1. https://github.com/tarantool/tarantool/actions/runs/5411519721/jobs/9835738155
Follows #110

ci: fix luatest version

---

test/set_schema_test.lua

The fix for tarantool/tarantool#8649 always sets `index_object.parts.exclude_null` to `false` when it is actually `false`, however the test `set_schema_test.lua` fails [1], because it expects `index_object.parts` without the `exclude_null` field. This patch fixes the test so that it allows both `nil` and `false` for `exclude_null`.
1. https://github.com/tarantool/tarantool/actions/runs/5889232292/job/15972202950

test: align `set_schema_test.lua` with core `exclude_null` changes

---

test/set_schema_test.lua

The pull request tarantool/tarantool#8915 implements the key part sort order, which introduces a new `sort_order` field of index parts. This field is unexpected for the test and so it fails [1].
This patch fixes the test by allowing to have this part property.
1. https://github.com/tarantool/tarantool/actions/runs/6172230004/job/16752337479

test: align set_schema_test.lua with sort_order feature

---

.github/workflows/publish.yaml
.github/workflows/test.yml
CHANGELOG.md
README.md
ddl/check.lua
ddl/db.lua
deps.sh
test/check_schema_test.lua
test/helper.lua

Datetime intervals are supported as a part of space schema format since 2.10.0 [1]. They are not allowed to be a part of memtx index [2].
1. https://github.com/tarantool/tarantool/commit/a9e30fb365c1643484054aa07038c015383e7faa
2. https://github.com/tarantool/tarantool/blob/ddaa5a320ee8d8d1009e07bbf6b8fe5cb4acbb45/src/box/memtx_space.c#L844-L851

ddl: support interval type in format

---

CHANGELOG.md
ddl/version.lua

This is a patch release introducing datetime intervals support in the format.
- Added support of `interval` type for Tarantool 2.10+ space format (#117).

release 1.6.5

---

.github/workflows/reusable_test.yml

Bump version of the `actions/checkout` and `actions/download-artifact` actions to v4 for fixing the following GitHub warning:
Node.js 16 actions are deprecated.
Please update the following actions to use Node.js 20

ci: bump actions to v4 in reusable_test.yml

---

.luacheckrc
CHANGELOG.md
README.md
ddl.lua
ddl/check.lua
ddl/compare.lua
ddl/get.lua
ddl/set.lua
ddl/utils.lua
test/check_schema_test.lua
test/db.lua
test/get_schema_test.lua
test/set_schema_test.lua
test/set_schema_with_sequence_test.lua
test/utils_test.lua

This patch adds the support of sequences through new schema section, as well as proper support of sequence option for indexes. Before this patch, ddl had half-baked support of sequences: one could provide `sequence` as sequence name in indexes and it would be created. This approach was broken in basic `set_schema(get_schema)` scenario since there wasn't any sequences support in get. Current design is inspired by existing "not implemented yet" tests and documentation examples.
Closes #122

ddl: support sequences

---

deps.sh

dkjson rocks are installed by downloading some author-hosted tar.gz source archives. It seems that 2.5-2 version archive has been removed. (It's not available, yet 2.8-1 is ok.) We also change rockspec source to luarocks in the commit since GitHub repository for dkjson is archived since 2020 [1] while luarocks page is alive and receives new updates [2].
1. https://github.com/LuaDist/dkjson
2. https://luarocks.org/modules/dhkolf/dkjson

coverage: fix dkjson install
